### PR TITLE
Lint, Tests, CircleCI

### LINKED ISSUE #54: Xcode Log Reporting "UI API called on a background thread"
**Describe the bug**
I have been debugging a strange issue in which our app crashes. I don't believe the crash is related to Radar, but while pouring over the debug logs, I found an error being reported saying that a UI API was called in Radar's background thread.

**To Reproduce**
Steps to reproduce the behavior (as far as I can tell):
1. Open the Xcode log while running an instance of an app with React Native Radar
2. It should show up right near the other logs that happen during initialization.

**Expected behavior**
No error message.

**Screenshots**
Here is the error log:
```
2018-12-23 20:01:40.523586-0500 zonder[60193:2894435] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication backgroundTimeRemaining]
PID: 60193, TID: 2894435, Thread name: (none), Queue name: com.facebook.react.RNRadarQueue, QoS: 0
Backtrace:
4   zonder                              0x000000010f2bdddc -[RadarLocationManager requestLocationWithDelay] + 243
5   zonder                              0x000000010f2c6710 +[Radar startTrackingWithOptions:] + 283
6   zonder                              0x000000010f2d02f3 -[RNRadar startTracking:] + 131
7   CoreFoundation                      0x000000011744e03c __invoking___ + 140
8   CoreFoundation                      0x000000011744b4d5 -[NSInvocation invoke] + 325
9   CoreFoundation                      0x000000011744b926 -[NSInvocation invokeWithTarget:] + 54
10  zonder                              0x000000010e9f951a -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2810
11  zonder                              0x000000010eab5346 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 790
12  zonder                              0x000000010eab4e5f _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
13  zonder                              0x000000010eab4dd9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
14  libdispatch.dylib                   0x0000000118363595 _dispatch_call_block_and_release + 12
15  libdispatch.dylib                   0x0000000118364602 _dispatch_client_callout + 8
16  libdispatch.dylib                   0x000000011836bb0b _dispatch_lane_serial_drain + 791
17  libdispatch.dylib                   0x000000011836c784 _dispatch_lane_invoke + 428
18  libdispatch.dylib                   0x000000011837689a _dispatch_workloop_worker_thread + 733
19  libsystem_pthread.dylib             0x000000011875460b _pthread_wqthread + 409
20  libsystem_pthread.dylib             0x0000000118754405 start_wqthread + 13
```
**Metadata (please complete the following information):**
 - React Native Radar Version: 2.1.2 with latest iOS SDK
 - Platform: iOS
 - Device: Simulator
 - Device OS Version: iOS 12.1
 - React Native 0.57.8

### LINKED ISSUE #61: The callback trackOnce() exists in module RNRadar, but only one callback may be registered to a function in a native module.
**Describe the bug**
trackOnceWithCompletionHandler is calling its callback more than once and it is not allowed to resolve Promise twise or more 

**To Reproduce**
1. tracking has been started already 
2. call trackOnce it will result with Promised callback 
3. a few seconds later it will try to resolve again

**Expected behavior**
it needs to be called once 

**Screenshots**
image-1
image-2

**Metadata (please complete the following information):**
 - React Native Radar Version: [e.g. 2.1.2]
 - Platform: [both]
 - Device [iPhone X]
 - Device OS Version [12]

### PR DESCRIPTION
**Pull request by coolbrow**
( Continued from #58 )

Long overdue checks for this codebase:
- Lint checks for JS code
- Tests for JS
- Tests for Android
- Test for iOS 

~Will put these checks on CircleCI and they'll be a requirement for future changes.~ 🎉 Done!

Also:
- Fixes #54
- Fixes #61

### CODE REVIEW

**Comment by nickpatrick** [comment]
😍

**Comment by nickpatrick** [comment]
Love it! Looks good to me but suggest @tjulien and @kochis review as well.

File: android/src/test/java/io/radar/react/RNRadarModuleTest.java [hunk 1]
```diff
@@ -0,0 +1,249 @@
...
+
+    module.setDescription(description);
+
+    verifyStatic(Radar.class);
+    Radar.setDescription(description);
+  }
+
+  @Test
+  public void setPlacesProvider() {
+    String providerStr = "facebook2";
```
Comment (nickpatrick) [inline android/src/test/java/io/radar/react/RNRadarModuleTest.java]: facebook2?

File: ios/RNRadarTests/RNRadarTests.m [hunk 2]
```diff
@@ -0,0 +1,188 @@
+//
+//  RNRadarTests.m
+//  RNRadarTests
+//
+//  Created by Russell Cullen on 1/4/19.
+//  Copyright © 2019 Facebook. All rights reserved.
```
Comment (nickpatrick) [inline ios/RNRadarTests/RNRadarTests.m]: Let's remove the Facebook copyright headers

File: ios/RNRadarTests/RNRadarTests.m [hunk 3]
```diff
@@ -0,0 +1,188 @@
...
+- (void)tearDown {
+    [radarUtils stopMocking];
+    [radar stopMocking];
+    [super tearDown];
+}
+
+- (void)testSetUserId {
+    OCMStub([radar setUserId:[OCMArg any]]).andDo(nil);
+    
+    NSString* userId = @"someUserId123";
```
Comment (nickpatrick) [inline ios/RNRadarTests/RNRadarTests.m]: Stylistic thing but `NSString *userId` instead of `NSString* userId`. May want to add linting for native iOS and Android code as well.

File: android/src/test/java/io/radar/react/RNRadarModuleTest.java (hunk 1 above)
Comment (coolbrow) [reply android/src/test/java/io/radar/react/RNRadarModuleTest.java]: oops must've slipped, doesn't matter anyways since this is just a random string

File: .eslintrc [hunk 4]
```diff
@@ -1,9 +1,79 @@
...
+    "react",
+    "jest"
+  ],
   "rules": {
-    "import/extensions": 0,
-    "import/no-unresolved": [2, { "ignore": ["react"] }],
-    "no-underscore-dangle": 0
+    "consistent-return": 0,
+    "func-names": 0,
+    "jsx-a11y/accessible-emoji": 0,
```
Comment (tjulien) [inline .eslintrc]: would it make sense to `rm` all the jsx rules?

**Comment by irfaan** [comment]
Hi! Is the team id supposed to be hard-coded for tests? I'm getting `-1: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "96GHH65B9D" with a private key was found. (in target 'RNRadarTests')`

**Comment by coolbrow** [comment]
@irfaan - That is a small bug, nice find! It should be as simple as selecting `None` or your own development team from the team dropdown in the General tab of `RNRadarTests` target.
